name: CI

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@v1.15.4
      - name: cargo test
        run: cargo test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@v1.15.4
        with:
          components: clippy, rustfmt
      - name: cargo fmt
        run: cargo fmt --check
      - name: cargo clippy
        run: cargo clippy -- -D warnings
